language: node_js
node_js:
  - '0.10'
before_script:
  - npm run test-jshint
  - cp configs/database.example.js configs/database.js
  - cp configs/app.example.js configs/app.js
after_script:
  - npm run test-coverage
